const { PERSONA_FILTER_REASON, PERSONA_IMPORT_LIMITS } = require("../config/constants");

const AUTO_GENERATED_SUBJECT_PATTERNS = [
  /^auto(?:matic)? reply/i,
  /^out of office/i,
  /^automatic reply/i,
  /^undeliverable/i,
  /^undelivered mail/i,
  /^delivery status notification/i,
  /^mail delivery failed/i,
  /^calendar:/i,
  /^invitation:/i,
  /^accepted:/i,
  /^declined:/i,
  /^tentative:/i,
  /^re: invitation/i,
  /^your receipt/i,
  /^receipt for/i,
  /^order confirmation/i,
];

const AUTO_GENERATED_SENDER_PATTERNS = [
  /no-?reply@/i,
  /^donotreply@/i,
  /mailer-daemon@/i,
  /calendar-notification@/i,
  /postmaster@/i,
];

function extractDomain(emailAddress) {
  if (!emailAddress) return "";
  const match = emailAddress.match(/@([^\s>]+)/);
  return match ? match[1].toLowerCase() : "";
}

/** First address in a header value that may contain a display name
 * ("Jane Doe <jane@acme.com>") or a comma-separated list — only the first
 * recipient's domain is used for the internal/external check. */
function extractFirstAddress(headerValue) {
  if (!headerValue) return "";
  const first = headerValue.split(",")[0].trim();
  const angleMatch = first.match(/<([^>]+)>/);
  return (angleMatch ? angleMatch[1] : first).trim();
}

function isInternalRecipient(recipientDomain, senderDomain) {
  if (!recipientDomain || !senderDomain) return false;
  return recipientDomain.toLowerCase() === senderDomain.toLowerCase();
}

function isAutoGenerated({ subject, fromEmail }) {
  const normalizedSubject = (subject || "").trim();
  const normalizedFrom = (fromEmail || "").trim();

  if (AUTO_GENERATED_SUBJECT_PATTERNS.some((pattern) => pattern.test(normalizedSubject))) {
    return true;
  }

  if (AUTO_GENERATED_SENDER_PATTERNS.some((pattern) => pattern.test(normalizedFrom))) {
    return true;
  }

  return false;
}

function isLengthOutOfRange(bodyText, { min, max } = {}) {
  const length = (bodyText || "").trim().length;
  const minChars = min ?? PERSONA_IMPORT_LIMITS.MIN_BODY_CHARS;
  const maxChars = max ?? PERSONA_IMPORT_LIMITS.MAX_BODY_CHARS;

  if (length < minChars) return "short";
  if (length > maxChars) return "long";
  return null;
}

/** Normalizes a subject+body pair into a dedup key — near-identical template
 * sends (same copy, different recipient) collapse onto the same key.
 * Deliberately simple exact-match-after-normalization, not fuzzy similarity:
 * strips whitespace differences and common merge-field-shaped tokens
 * ({{name}}, [Company]) so a templated blast dedupes even though the
 * greeting/company name differs per recipient. */
function dedupeKey(subject, bodyText) {
  const normalize = (value) =>
    (value || "")
      .toLowerCase()
      .replace(/\{\{[^}]*\}\}/g, "")
      .replace(/\[[^\]]*\]/g, "")
      .replace(/\s+/g, " ")
      .trim();

  return `${normalize(subject)}::${normalize(bodyText)}`;
}

/** Runs all baseline filters (PRD 5.3) against one parsed sent message and
 * returns the reason it should start unchecked, or null if it's a clean,
 * high-confidence candidate (starts pre-checked per PRD 5.4). */
function classifySentEmail({ subject, bodyText, fromEmail, recipientDomain, senderDomain }) {
  if (isInternalRecipient(recipientDomain, senderDomain)) {
    return PERSONA_FILTER_REASON.INTERNAL_RECIPIENT;
  }

  if (isAutoGenerated({ subject, fromEmail })) {
    return PERSONA_FILTER_REASON.AUTO_GENERATED;
  }

  const lengthIssue = isLengthOutOfRange(bodyText);
  if (lengthIssue === "short") return PERSONA_FILTER_REASON.TOO_SHORT;
  if (lengthIssue === "long") return PERSONA_FILTER_REASON.TOO_LONG;

  return null;
}

module.exports = {
  extractDomain,
  extractFirstAddress,
  isInternalRecipient,
  isAutoGenerated,
  isLengthOutOfRange,
  dedupeKey,
  classifySentEmail,
};
